---
abstract: 'Calculates Association Coefficients of Nominal Scale.'
author:
  - 'takeshi miki <miki@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Associations
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00003
